# Generated by Django 2.2.16 on 2023-03-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230318_2345'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_not_author',
        ),
    ]
